inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/dummy/db/**/*'
    - 'test/dummy/config/**/*'
    - 'test/dummy/script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'vendor/**'
Metrics/AbcSize:
  Max: 35
Style/SpaceInsideBrackets:
  Enabled: false # spaces make enums in models more readable
Metrics/MethodLength:
  Max: 20