sudo: required
dist: trusty
language: ruby
rvm:
 - 2.5.1
before_install:
 - gem update --system
 - gem install bundler
script:
  - bundle exec rubocop
notifications:
  irc:
    channels:
      - "irc.barafranca.com#dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
    skip_join: true