sudo: required
dist: trusty
language: ruby
rvm:
 - 2.4.0
before_install: gem install bundler
script:
  - bundle exec rubocop -R
notifications:
  irc:
    channels:
      - "irc.barafranca.com#dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
    skip_join: true